lessons:
  outputs:
    dev:
      type: duckdb
      path: 'D:\prj\dbt-tutorial-course\source_database\thelook_source.db'
      threads: 4

    prod:
      type: duckdb
      path: prod.duckdb
      threads: 4

  target: dev
