thelook_project:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: 'D:\prj\dbt-tutorial-course\target_database\thelook_final.db'
      
      # Zmiana: attachments → attach
      attach:
        - path: 'D:\prj\dbt-tutorial-course\source_database\thelook_source.db'
          alias: source_db
          read_only: true  # opcjonalnie, ale zalecane dla bazy źródłowej
      
      extensions: []
      settings:
        custom_extension_repository: ""