thelook_project: # nazwa musi zgadzać się z profile w dbt_project.yml
  target: dev
  outputs:
    dev:
      type: duckdb
      path: '..\target_database\thelook_final.db' # Tutaj dbt będzie tworzyć tabele/widoki
      extensions:
        - parquet
      # Tutaj "podpinamy" Twoją bazę źródłową jako zewnętrzną bazę danych
      attach:
        - path: '..\source_database\thelook_source.db'
          alias: source_db # alias, pod którym dbt widzi te dane